# Generated by Django 5.2.8 on 2025-11-24 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_guestsession_checkout_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('duration_in_minutes', models.IntegerField()),
                ('data_limit_in_mbz', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='guestsession',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.wifiplan'),
        ),
    ]
